apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Sonar-qube-excel-extractor
  name: Sonar-qube-excel-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Sonar-qube-excel-extractor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Sonar-qube-excel-extractor
    spec:
      containers:
      - image: hiteshdutt/sonar-server-excel-extractor:latest
        command: ["/bin/sh",  "-c",  "envsubst < /usr/cmconfig/appsettings.js > /app/dist/config/appsettings.js && node /app/dist/index.read.js"]
        imagePullPolicy: Always
        name: Sonar-qube-excel-extractor
        env:
        - name: LOGGING_FILE_PATH
          value: "/app/logs/"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/cmconfig
          name: Sonar-qube-excel-extractor-cm-volume
      volumes:
      - name: Sonar-qube-excel-extractor-cm-volume
        configMap:
          name: sonar-qube-excel-extractor-config