name: Docker Build and Push

on:
    workflow_dispatch:

    push:
        branches:
        - main

jobs:
    DockerBuildPush:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.5
              with:
                  fetch-depth: 0
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                # list of Docker images to use as base name for tags
                images: hiteshdutt/sonar-server-excel-extractor           
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=raw,value=latest,enable={{is_default_branch}}
                  type=ref,event=branch
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha         
            - name: Login to DockerHub
              uses: docker/login-action@v3.1.0
              with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build & push
              uses: docker/build-push-action@v5.3.0
              with: 
                    file: ./Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}